#!/usr/bin/env bash
set -eo pipefail
if [ ! -d examples ] ; then
	echo Please run this script from the root of the CHERIoT book-examples repository.
	exit 1
fi
CLANG_TIDY=/cheriot-tools/bin/clang-tidy
CLANG_FORMAT=/cheriot-tools/bin/clang-format
if [ -n "$1" ] ; then
	CLANG_TIDY=$1/clang-tidy
	CLANG_FORMAT=$1/clang-format
fi
if [ ! -x ${CLANG_TIDY} ] ; then
	echo Usage: $0 path/to/cheriot/tools/bin
	echo clang-tidy not found at ${CLANG_TIDY}
	exit 1
fi
if [ ! -x ${CLANG_FORMAT} ] ; then
	echo Usage: $0 path/to/cheriot/tools/bin
	echo clang-format not found at ${CLANG_FORMAT}
	exit 1
fi

if which nproc ; then
	PARALLEL_JOBS=$(nproc)
else
	PARALLEL_JOBS=$(sysctl -n kern.smp.cpus)
fi


# Exclude the two files generated by BearSSL from formatting.
FILES=$(find examples -name '*.h' -or -name '*.hh' -or -name '*.cc' -or -name '*.c' | grep -v 'DigiCertGlobalRootG2' | grep -v mosquitto.org.h)

${CLANG_FORMAT} -i ${FILES}
if ! git diff --exit-code ${HEADERS} ${SOURCES} ; then
	echo clang-format applied changes
	exit 1
fi
